baseURL = "https://empijei.science/cooking/"
languageCode = "en-us"
title = "Cooking with the flow"
theme = "gochowdown"
defaultcontentlanguage= "en"
paginate= 20
canonifyurls= true
[permalinks]
posts = "/posts/:year/:month/:title"

[params]
author = "Roberto Clapis"
description = "Recipes made by a software engineer"
keywords = "recipes"
favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"
footercontent = ""
hidecredits = false 
hidecopyright = false
showNavTitle = false
custom_css = [
  "style.css"
]

[menu]

  [[menu.main]]
  name = "Home"
  weight = 1.0
  url = "/"

  [[menu.main]]
  name = "Categories"
  weight = 2.0
  url = "/category/"

  [[menu.main]]
  name = "Cuisines"
  weight = 3.0
  url = "/cuisine/"

  [[menu.main]]
  name = "Tags"
  weight = 4.0
  url = "/tags/"

[taxonomies]
category = "category"
cusine = "cuisine"
tag = "tags"